--------------------------------------------------------
--  Constraints for Table BGH_ROAMINGDETAILLIST
--------------------------------------------------------

  ALTER TABLE "BGH"."BGH_ROAMINGDETAILLIST" ADD CONSTRAINT "PK_BGH_ROAMINGDETLIST" PRIMARY KEY ("SH_DES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE"  ENABLE;
  ALTER TABLE "BGH"."BGH_ROAMINGDETAILLIST" MODIFY ("SH_DES" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BGH_ROAMINGDETAILLIST" MODIFY ("ENTRY_DATE" NOT NULL ENABLE);
