--------------------------------------------------------
--  DDL for Trigger BGH_HISTORY_ON_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "BGH"."BGH_HISTORY_ON_INSERT" 
  BEFORE INSERT ON BGH.BGH_HISTORY
  FOR EACH ROW
BEGIN
  IF INSERTING THEN
    SELECT BGH_HISTORY_MAX_ID.NEXTVAL INTO :NEW.BGH_HIST_ID FROM DUAL;
	END IF;
END BGH_HISTORY_ON_INSERT;

/
ALTER TRIGGER "BGH"."BGH_HISTORY_ON_INSERT" ENABLE;
