--------------------------------------------------------
--  Constraints for Table BGH_SERVICE_VARIANT
--------------------------------------------------------

  ALTER TABLE "BGH"."BGH_SERVICE_VARIANT" ADD CONSTRAINT "PK_BGH_SERVICE_VARIANT" PRIMARY KEY ("SNSHDES", "VARIANT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 32768 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE"  ENABLE;
  ALTER TABLE "BGH"."BGH_SERVICE_VARIANT" ADD CONSTRAINT "C_CHECK_VARIANT" CHECK (VARIANT NOT IN ('M', 'E', 'O', 'A', 'H', 'P', 'C', 'FG')) ENABLE;
  ALTER TABLE "BGH"."BGH_SERVICE_VARIANT" MODIFY ("SNSHDES" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BGH_SERVICE_VARIANT" MODIFY ("VARIANT" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BGH_SERVICE_VARIANT" MODIFY ("ENTRY_DATE" NOT NULL ENABLE);
