--------------------------------------------------------
--  DDL for Trigger BGH_CHARGE_ITEM_CONFIG_ON_INS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "BGH"."BGH_CHARGE_ITEM_CONFIG_ON_INS" 
  BEFORE INSERT ON BGH.BGH_CHARGE_ITEM_CONFIGURATION
  FOR EACH ROW
BEGIN
  IF INSERTING THEN
    SELECT BGH.BGH_CHARGE_ITEM_CONFIG_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END BGH_CHARGE_ITEM_CONFIG_ON_INS;

/
ALTER TRIGGER "BGH"."BGH_CHARGE_ITEM_CONFIG_ON_INS" ENABLE;
