--------------------------------------------------------
--  DDL for Table BGH_INVOICE_GROUPS
--------------------------------------------------------

  CREATE TABLE "BGH"."BGH_INVOICE_GROUPS" 
   (	"GROUP_ID" NUMBER(*,0), 
	"GROUP_SORT_ORDER" NUMBER(*,0), 
	"GROUP_VARIANT" VARCHAR2(1 BYTE), 
	"GROUP_DESC" VARCHAR2(100 BYTE), 
	"GROUP_DESC_EN" VARCHAR2(100 BYTE), 
	"FORMAT" VARCHAR2(10 BYTE), 
	"SHOWN" VARCHAR2(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE" ;
