--------------------------------------------------------
--  DDL for Table BGH_HISTORY
--------------------------------------------------------

  CREATE TABLE "BGH"."BGH_HISTORY" 
   (	"BGH_HIST_ID" NUMBER, 
	"PROCESS_ID" NUMBER, 
	"PROCESS_NUM" NUMBER, 
	"PARENT_PROCESS_ID" NUMBER DEFAULT 0, 
	"CMD_ARGS" VARCHAR2(256 BYTE), 
	"BGH_LOG_FILE" VARCHAR2(256 BYTE), 
	"START_DATE" DATE, 
	"STOP_DATE" DATE, 
	"MIN_BILLSEQNO" NUMBER, 
	"MAX_BILLSEQNO" NUMBER, 
	"NUM_SINGLE_INVOICES" NUMBER, 
	"SINGLE_PROC_TIME" NUMBER(20,4), 
	"NUM_MULTI_INVOICES" NUMBER, 
	"MULTI_PROC_TIME" NUMBER(20,4), 
	"NUM_INV_SUBSCR" NUMBER, 
	"NUM_INV_CONTR" NUMBER, 
	"AIRTIME_CONTR" NUMBER, 
	"NUM_EBMAIN_FLAT_INV" NUMBER, 
	"NUM_EBMAIN_CORP_INV" NUMBER, 
	"TOT_INV_AMT" NUMBER(20,4), 
	"NUM_KAPPA_INVOICES" NUMBER, 
	"KAPPA_PROC_TIME" NUMBER(20,4), 
	"NUM_PROC_SUBSCR" NUMBER DEFAULT 0, 
	"NUM_PROC_CONTR" NUMBER DEFAULT 0, 
	"NUM_PROC_CALLS" NUMBER DEFAULT 0, 
	"BGH_VERSION" VARCHAR2(15 BYTE), 
	"SVD_VERSION" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 2457600 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE" ;
