--------------------------------------------------------
--  DDL for Trigger BGH_INVOICE_GROUP_RULES_ON_INS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "BGH"."BGH_INVOICE_GROUP_RULES_ON_INS" 
  BEFORE INSERT ON BGH.BGH_INVOICE_GROUP_RULES
  FOR EACH ROW
BEGIN
  IF INSERTING THEN
    SELECT BGH.BGH_INVOICE_GROUP_RULES_SEQ.NEXTVAL INTO :NEW.RULE_ID FROM DUAL;
  END IF;
END FP_GROUP_RULES_NEW_ON_INS;

/
ALTER TRIGGER "BGH"."BGH_INVOICE_GROUP_RULES_ON_INS" ENABLE;
