--------------------------------------------------------
--  DDL for Table BGH_SERVICE_VARIANT
--------------------------------------------------------

  CREATE TABLE "BGH"."BGH_SERVICE_VARIANT" 
   (	"SNSHDES" VARCHAR2(5 BYTE), 
	"VARIANT" VARCHAR2(10 BYTE), 
	"ENTRY_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 20 PCTUSED 40 INITRANS 5 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 32768 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE" ;
