--------------------------------------------------------
--  DDL for Table BGH_ROAMINGDETAILLIST
--------------------------------------------------------

  CREATE TABLE "BGH"."BGH_ROAMINGDETAILLIST" 
   (	"ROAMING_DETAIL_E" VARCHAR2(1 BYTE), 
	"SH_DES" VARCHAR2(5 BYTE), 
	"LONG_DES" VARCHAR2(250 BYTE), 
	"ENTRY_DATE" DATE DEFAULT SYSDATE, 
	"COMMENT_R" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE" ;
