--------------------------------------------------------
--  Ref Constraints for Table BGH_CHARGE_ITEM_CONFIGURATION
--------------------------------------------------------

  ALTER TABLE "BGH"."BGH_CHARGE_ITEM_CONFIGURATION" ADD FOREIGN KEY ("CHARGE_TYPE")
	  REFERENCES "BGH"."PRODUCT_TYPES" ("PRODUCT_TYPE_SHORT_DESC") ENABLE;
  ALTER TABLE "BGH"."BGH_CHARGE_ITEM_CONFIGURATION" ADD FOREIGN KEY ("FORMAT")
	  REFERENCES "BGH"."PRODUCT_FORMAT" ("FORMAT_SHDES") ENABLE;
  ALTER TABLE "BGH"."BGH_CHARGE_ITEM_CONFIGURATION" ADD FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "BGH"."PRODUCTS" ("PRODUCT_ID") ENABLE;
  ALTER TABLE "BGH"."BGH_CHARGE_ITEM_CONFIGURATION" ADD FOREIGN KEY ("ITEMIZED_PRODUCT_ID")
	  REFERENCES "BGH"."PRODUCTS" ("PRODUCT_ID") ENABLE;
