REM INSERTING into BGH.BGH_INVOICE_GROUPS
SET DEFINE OFF;
Insert into BGH.BGH_INVOICE_GROUPS (GROUP_ID,GROUP_SORT_ORDER,GROUP_VARIANT,GROUP_DESC,GROUP_DESC_EN,FORMAT,SHOWN) values (1,0,'M','Maandkosten','Monthly Charges','NO_FORMAT','Y');
Insert into BGH.BGH_INVOICE_GROUPS (GROUP_ID,GROUP_SORT_ORDER,GROUP_VARIANT,GROUP_DESC,GROUP_DESC_EN,FORMAT,SHOWN) values (2,1,'E','Gebruikskosten','Usage Charges','NO_FORMAT','Y');
Insert into BGH.BGH_INVOICE_GROUPS (GROUP_ID,GROUP_SORT_ORDER,GROUP_VARIANT,GROUP_DESC,GROUP_DESC_EN,FORMAT,SHOWN) values (3,3,'O','Kortingen/overige kosten','Discounts/Other Costs','NO_FORMAT','Y');
Insert into BGH.BGH_INVOICE_GROUPS (GROUP_ID,GROUP_SORT_ORDER,GROUP_VARIANT,GROUP_DESC,GROUP_DESC_EN,FORMAT,SHOWN) values (4,4,'P','Toestelkredieten','Handset Credits','NO_FORMAT','Y');
