--------------------------------------------------------
--  DDL for Table BUNDLE_CODES
--------------------------------------------------------

  CREATE TABLE "BGH"."BUNDLE_CODES" 
   (	"BUNDLE_ID" NUMBER(22,0), 
	"BUNDLE_CODE" VARCHAR2(5 BYTE), 
	"BUNDLE_DES" VARCHAR2(100 BYTE), 
	"BUNDLE_UOM" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE" ;
