--------------------------------------------------------
--  Constraints for Table BUNDLE_CODES
--------------------------------------------------------

  ALTER TABLE "BGH"."BUNDLE_CODES" ADD CONSTRAINT "PK_BUC_ID" PRIMARY KEY ("BUNDLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE"  ENABLE;
  ALTER TABLE "BGH"."BUNDLE_CODES" MODIFY ("BUNDLE_ID" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BUNDLE_CODES" MODIFY ("BUNDLE_CODE" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BUNDLE_CODES" MODIFY ("BUNDLE_UOM" NOT NULL ENABLE);
