--------------------------------------------------------
--  DDL for Index PK_BUC_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "BGH"."PK_BUC_ID" ON "BGH"."BUNDLE_CODES" ("BUNDLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE" ;
