--------------------------------------------------------
--  DDL for Index PK_PRODUCT_FORMAT_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "BGH"."PK_PRODUCT_FORMAT_ID" ON "BGH"."PRODUCT_FORMAT" ("FORMAT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE" ;
