--------------------------------------------------------
--  DDL for Index PK_STRING_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "BGH"."PK_STRING_ID" ON "BGH"."BGH_STRING_TABLE" ("STRING_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 122880 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE" ;
