--------------------------------------------------------
--  Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "BGH"."PRODUCTS" ADD PRIMARY KEY ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE"  ENABLE;
  ALTER TABLE "BGH"."PRODUCTS" ADD CONSTRAINT "C_CHECK_PRODUCTS_BDOWN_C12" CHECK (( PRODUCT_TYPE_ID in (3) AND BREAKDOWN_SHDES IS NOT NULL )
          OR
          ( PRODUCT_TYPE_ID not in (3) AND BREAKDOWN_SHDES IS NULL )) ENABLE;
  ALTER TABLE "BGH"."PRODUCTS" ADD CONSTRAINT "C_CHECK_PRODUCTS_BLOCK_RND_C12" CHECK (BLOCK_ROUNDED IS NULL OR BLOCK_ROUNDED IN ('X')) ENABLE;
  ALTER TABLE "BGH"."PRODUCTS" ADD CONSTRAINT "C_CHECK_PRODUCTS_ROAMDET_C12" CHECK (ROAMING_DETAILS IS NULL OR ROAMING_DETAILS IN ('X')) ENABLE;
  ALTER TABLE "BGH"."PRODUCTS" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "BGH"."PRODUCTS" MODIFY ("PRODUCT_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "BGH"."PRODUCTS" MODIFY ("USAGE_BEHAVIOUR_ID" NOT NULL ENABLE);
  ALTER TABLE "BGH"."PRODUCTS" MODIFY ("EVENTS_BEHAVIOUR_ID" NOT NULL ENABLE);
  ALTER TABLE "BGH"."PRODUCTS" MODIFY ("VOLUME_BEHAVIOUR_ID" NOT NULL ENABLE);
  ALTER TABLE "BGH"."PRODUCTS" MODIFY ("VARIANT_ID" NOT NULL ENABLE);
  ALTER TABLE "BGH"."PRODUCTS" MODIFY ("PRODUCT_DESC" NOT NULL ENABLE);
  ALTER TABLE "BGH"."PRODUCTS" MODIFY ("ENTRY_DATE" NOT NULL ENABLE);
