--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------

  CREATE TABLE "BGH"."PRODUCTS" 
   (	"PRODUCT_ID" NUMBER, 
	"PRODUCT_TYPE_ID" NUMBER, 
	"USAGE_BEHAVIOUR_ID" NUMBER(*,0) DEFAULT 1, 
	"EVENTS_BEHAVIOUR_ID" NUMBER(*,0) DEFAULT 1, 
	"VOLUME_BEHAVIOUR_ID" NUMBER(*,0) DEFAULT 2, 
	"VARIANT_ID" NUMBER(*,0) DEFAULT 0, 
	"PRODUCT_DESC" VARCHAR2(80 BYTE), 
	"PRODUCT_DESC_EN" VARCHAR2(80 BYTE), 
	"ENTRY_DATE" DATE DEFAULT SYSDATE, 
	"BREAKDOWN_SHDES" VARCHAR2(5 BYTE), 
	"ROAMING_DETAILS" VARCHAR2(1 BYTE), 
	"BLOCK_ROUNDED" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE" ;
