--------------------------------------------------------
--  Constraints for Table PRODUCT_FORMAT
--------------------------------------------------------

  ALTER TABLE "BGH"."PRODUCT_FORMAT" ADD CONSTRAINT "PK_PRODUCT_FORMAT_ID" PRIMARY KEY ("FORMAT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE"  ENABLE;
  ALTER TABLE "BGH"."PRODUCT_FORMAT" ADD CONSTRAINT "UC_PRODUCT_FORMAT" UNIQUE ("FORMAT_SHDES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE"  ENABLE;
  ALTER TABLE "BGH"."PRODUCT_FORMAT" MODIFY ("FORMAT_ID" NOT NULL ENABLE);
  ALTER TABLE "BGH"."PRODUCT_FORMAT" MODIFY ("FORMAT_SHDES" NOT NULL ENABLE);
  ALTER TABLE "BGH"."PRODUCT_FORMAT" MODIFY ("FORMAT_DES" NOT NULL ENABLE);
