--------------------------------------------------------
--  Constraints for Table PRODUCTS_VARIANT
--------------------------------------------------------

  ALTER TABLE "BGH"."PRODUCTS_VARIANT" ADD PRIMARY KEY ("VARIANT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE"  ENABLE;
  ALTER TABLE "BGH"."PRODUCTS_VARIANT" ADD CONSTRAINT "UC_PRODUCTS_VARIANT" UNIQUE ("VARIANT_SHDES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE"  ENABLE;
  ALTER TABLE "BGH"."PRODUCTS_VARIANT" MODIFY ("VARIANT_ID" NOT NULL ENABLE);
  ALTER TABLE "BGH"."PRODUCTS_VARIANT" MODIFY ("VARIANT_SHDES" NOT NULL ENABLE);
  ALTER TABLE "BGH"."PRODUCTS_VARIANT" MODIFY ("VARIANT_DES" NOT NULL ENABLE);
