--------------------------------------------------------
--  Ref Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "BGH"."PRODUCTS" ADD FOREIGN KEY ("PRODUCT_TYPE_ID")
	  REFERENCES "BGH"."PRODUCT_TYPES" ("PRODUCT_TYPE_ID") ENABLE;
  ALTER TABLE "BGH"."PRODUCTS" ADD FOREIGN KEY ("VOLUME_BEHAVIOUR_ID")
	  REFERENCES "BGH"."PRODUCTS_VOLUME_BEHAVIOUR" ("PVB_ID") ENABLE;
  ALTER TABLE "BGH"."PRODUCTS" ADD FOREIGN KEY ("EVENTS_BEHAVIOUR_ID")
	  REFERENCES "BGH"."PRODUCTS_EVENTS_BEHAVIOUR" ("PEB_ID") ENABLE;
  ALTER TABLE "BGH"."PRODUCTS" ADD FOREIGN KEY ("VARIANT_ID")
	  REFERENCES "BGH"."PRODUCTS_VARIANT" ("VARIANT_ID") ENABLE;
  ALTER TABLE "BGH"."PRODUCTS" ADD FOREIGN KEY ("USAGE_BEHAVIOUR_ID")
	  REFERENCES "BGH"."PRODUCTS_USAGE_BEHAVIOUR" ("PUB_ID") ENABLE;
