REM INSERTING into BGH.PRODUCT_TYPES
SET DEFINE OFF;
Insert into BGH.PRODUCT_TYPES (PRODUCT_TYPE_ID,PRODUCT_TYPE_DESC,PRODUCT_TYPE_SHORT_DESC) values (1,'Access fees','A');
Insert into BGH.PRODUCT_TYPES (PRODUCT_TYPE_ID,PRODUCT_TYPE_DESC,PRODUCT_TYPE_SHORT_DESC) values (2,'Subscription fees','S');
Insert into BGH.PRODUCT_TYPES (PRODUCT_TYPE_ID,PRODUCT_TYPE_DESC,PRODUCT_TYPE_SHORT_DESC) values (3,'Usage fees','U');
Insert into BGH.PRODUCT_TYPES (PRODUCT_TYPE_ID,PRODUCT_TYPE_DESC,PRODUCT_TYPE_SHORT_DESC) values (4,'Other charges','O');
Insert into BGH.PRODUCT_TYPES (PRODUCT_TYPE_ID,PRODUCT_TYPE_DESC,PRODUCT_TYPE_SHORT_DESC) values (5,'Discounts & credits','P');
Insert into BGH.PRODUCT_TYPES (PRODUCT_TYPE_ID,PRODUCT_TYPE_DESC,PRODUCT_TYPE_SHORT_DESC) values (6,'Free Units','F');
