--------------------------------------------------------
--  DDL for Index UC_BGH_INVOICE_GROUPS_04
--------------------------------------------------------

  CREATE UNIQUE INDEX "BGH"."UC_BGH_INVOICE_GROUPS_04" ON "BGH"."BGH_INVOICE_GROUPS" ("GROUP_ID", "GROUP_DESC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE" ;
