--------------------------------------------------------
--  DDL for Index UC_PRODUCT_FORMAT
--------------------------------------------------------

  CREATE UNIQUE INDEX "BGH"."UC_PRODUCT_FORMAT" ON "BGH"."PRODUCT_FORMAT" ("FORMAT_SHDES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE" ;
