--------------------------------------------------------
--  DDL for Table BGH_STRING_TABLE
--------------------------------------------------------

  CREATE TABLE "BGH"."BGH_STRING_TABLE" 
   (	"STRING_ID" NUMBER, 
	"STRING_LABEL" VARCHAR2(100 BYTE), 
	"STRING_DES" VARCHAR2(500 BYTE), 
	"STRING_DES_EN" VARCHAR2(500 BYTE), 
	"COMMENTS" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 122880 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE" ;
