--------------------------------------------------------
--  Constraints for Table BGH_INVOICE_GROUPS
--------------------------------------------------------

  ALTER TABLE "BGH"."BGH_INVOICE_GROUPS" ADD CONSTRAINT "PK_BGH_INVOICE_GROUPS" PRIMARY KEY ("GROUP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE"  ENABLE;
  ALTER TABLE "BGH"."BGH_INVOICE_GROUPS" ADD CONSTRAINT "UC_BGH_INVOICE_GROUPS_01" UNIQUE ("GROUP_SORT_ORDER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE"  ENABLE;
  ALTER TABLE "BGH"."BGH_INVOICE_GROUPS" ADD CONSTRAINT "UC_BGH_INVOICE_GROUPS_02" UNIQUE ("GROUP_DESC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE"  ENABLE;
  ALTER TABLE "BGH"."BGH_INVOICE_GROUPS" ADD CONSTRAINT "UC_BGH_INVOICE_GROUPS_03" UNIQUE ("GROUP_DESC_EN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE"  ENABLE;
  ALTER TABLE "BGH"."BGH_INVOICE_GROUPS" ADD CONSTRAINT "UC_BGH_INVOICE_GROUPS_04" UNIQUE ("GROUP_ID", "GROUP_DESC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE"  ENABLE;
  ALTER TABLE "BGH"."BGH_INVOICE_GROUPS" ADD CONSTRAINT "UC_BGH_INVOICE_GROUPS_05" UNIQUE ("GROUP_ID", "GROUP_DESC_EN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE"  ENABLE;
  ALTER TABLE "BGH"."BGH_INVOICE_GROUPS" ADD CONSTRAINT "CON_CHECK_SHOWN" CHECK (SHOWN IN ('Y', 'N')) ENABLE;
  ALTER TABLE "BGH"."BGH_INVOICE_GROUPS" MODIFY ("GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BGH_INVOICE_GROUPS" MODIFY ("GROUP_SORT_ORDER" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BGH_INVOICE_GROUPS" MODIFY ("GROUP_VARIANT" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BGH_INVOICE_GROUPS" MODIFY ("GROUP_DESC" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BGH_INVOICE_GROUPS" MODIFY ("GROUP_DESC_EN" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BGH_INVOICE_GROUPS" MODIFY ("SHOWN" NOT NULL ENABLE);
