--------------------------------------------------------
--  Constraints for Table BGH_HISTORY
--------------------------------------------------------

  ALTER TABLE "BGH"."BGH_HISTORY" ADD CONSTRAINT "PK_BGH_HIST_ID" PRIMARY KEY ("BGH_HIST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 368640 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE"  ENABLE;
  ALTER TABLE "BGH"."BGH_HISTORY" MODIFY ("BGH_HIST_ID" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BGH_HISTORY" MODIFY ("PROCESS_ID" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BGH_HISTORY" MODIFY ("PROCESS_NUM" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BGH_HISTORY" MODIFY ("PARENT_PROCESS_ID" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BGH_HISTORY" MODIFY ("CMD_ARGS" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BGH_HISTORY" MODIFY ("BGH_LOG_FILE" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BGH_HISTORY" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BGH_HISTORY" MODIFY ("MIN_BILLSEQNO" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BGH_HISTORY" MODIFY ("MAX_BILLSEQNO" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BGH_HISTORY" MODIFY ("NUM_SINGLE_INVOICES" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BGH_HISTORY" MODIFY ("SINGLE_PROC_TIME" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BGH_HISTORY" MODIFY ("NUM_MULTI_INVOICES" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BGH_HISTORY" MODIFY ("MULTI_PROC_TIME" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BGH_HISTORY" MODIFY ("NUM_INV_SUBSCR" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BGH_HISTORY" MODIFY ("NUM_INV_CONTR" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BGH_HISTORY" MODIFY ("AIRTIME_CONTR" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BGH_HISTORY" MODIFY ("NUM_EBMAIN_FLAT_INV" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BGH_HISTORY" MODIFY ("NUM_EBMAIN_CORP_INV" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BGH_HISTORY" MODIFY ("TOT_INV_AMT" NOT NULL ENABLE);
