--------------------------------------------------------
--  Constraints for Table BGH_STRING_TABLE
--------------------------------------------------------

  ALTER TABLE "BGH"."BGH_STRING_TABLE" ADD CONSTRAINT "PK_STRING_ID" PRIMARY KEY ("STRING_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 122880 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE"  ENABLE;
  ALTER TABLE "BGH"."BGH_STRING_TABLE" ADD CONSTRAINT "BGH_STRING_TABLE_U01" UNIQUE ("STRING_LABEL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE"  ENABLE;
  ALTER TABLE "BGH"."BGH_STRING_TABLE" ADD CONSTRAINT "UC_BGH_STRING_TABLE" UNIQUE ("STRING_LABEL", "STRING_DES", "STRING_DES_EN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 122880 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE"  ENABLE;
  ALTER TABLE "BGH"."BGH_STRING_TABLE" MODIFY ("STRING_ID" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BGH_STRING_TABLE" MODIFY ("STRING_LABEL" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BGH_STRING_TABLE" MODIFY ("STRING_DES" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BGH_STRING_TABLE" MODIFY ("STRING_DES_EN" NOT NULL ENABLE);
