--------------------------------------------------------
--  DDL for Table BGH_INVOICE_GROUP_RULES
--------------------------------------------------------

  CREATE TABLE "BGH"."BGH_INVOICE_GROUP_RULES" 
   (	"RULE_ID" NUMBER(*,0), 
	"RULE_SORT_ORDER" NUMBER(*,0), 
	"VARIANT_RULE" VARCHAR2(10 BYTE) DEFAULT '*', 
	"TYPE_RULE" VARCHAR2(1 BYTE) DEFAULT '*', 
	"DESC_RULE" VARCHAR2(100 BYTE) DEFAULT '*', 
	"SIGN_RULE" NUMBER(*,0) DEFAULT 0, 
	"TMSHDES_RULE" VARCHAR2(5 BYTE) DEFAULT '*', 
	"SPSHDES_RULE" VARCHAR2(5 BYTE) DEFAULT '*', 
	"SNSHDES_RULE" VARCHAR2(5 BYTE) DEFAULT '*', 
	"USAGE_BEHAVIOUR_RULE" VARCHAR2(15 BYTE) DEFAULT '*', 
	"GROUP_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 122880 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE" ;
