--------------------------------------------------------
--  DDL for Table BGH_CHARGE_ITEM_CONFIGURATION
--------------------------------------------------------

  CREATE TABLE "BGH"."BGH_CHARGE_ITEM_CONFIGURATION" 
   (	"ID" NUMBER, 
	"CHARGE_TYPE" VARCHAR2(1 BYTE), 
	"XTMSHDES" VARCHAR2(5 BYTE), 
	"XTMCODE" NUMBER(*,0), 
	"XSPSHDES" VARCHAR2(5 BYTE), 
	"XSPCODE" NUMBER(*,0), 
	"SNSHDES" VARCHAR2(5 BYTE), 
	"SNCODE" NUMBER(*,0), 
	"USGSHDES" VARCHAR2(10 BYTE), 
	"USGIND" NUMBER(*,0), 
	"ZNSHDES" VARCHAR2(5 BYTE), 
	"ZNCODE" NUMBER(*,0), 
	"RTSHDES" VARCHAR2(5 BYTE), 
	"RTID" NUMBER(*,0), 
	"INFO1" VARCHAR2(10 BYTE), 
	"INFO2" VARCHAR2(30 BYTE), 
	"PAD" VARCHAR2(100 BYTE), 
	"PAV" VARCHAR2(100 BYTE), 
	"PRODUCT_ID" NUMBER(*,0) DEFAULT 0, 
	"ITEMIZED_PRODUCT_ID" NUMBER(*,0), 
	"FORMAT" VARCHAR2(10 BYTE) DEFAULT 'NO_FORMAT', 
	"DISPLAY_ZERO_CHARGE" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 532480 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE" ;
