--------------------------------------------------------
--  DDL for Trigger BGH_STRING_TABLE_ON_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "BGH"."BGH_STRING_TABLE_ON_INSERT" 
  BEFORE INSERT ON BGH.BGH_STRING_TABLE
  FOR EACH ROW
BEGIN
  IF INSERTING THEN
    SELECT BGH_STRING_TABLE_MAX_ID.NEXTVAL INTO :NEW.STRING_ID FROM DUAL;
	END IF;
END BGH_STRING_TABLE_ON_INSERT;

/
ALTER TRIGGER "BGH"."BGH_STRING_TABLE_ON_INSERT" ENABLE;
