--------------------------------------------------------
--  Constraints for Table BGH_INVOICE_GROUP_RULES
--------------------------------------------------------

  ALTER TABLE "BGH"."BGH_INVOICE_GROUP_RULES" ADD CONSTRAINT "PK_BGH_INVOICE_GROUP_RULES" PRIMARY KEY ("RULE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 122880 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE"  ENABLE;
  ALTER TABLE "BGH"."BGH_INVOICE_GROUP_RULES" ADD CONSTRAINT "UC_BGH_INVOICE_GROUP_RULES_01" UNIQUE ("VARIANT_RULE", "TYPE_RULE", "DESC_RULE", "SIGN_RULE", "TMSHDES_RULE", "SPSHDES_RULE", "SNSHDES_RULE", "USAGE_BEHAVIOUR_RULE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 122880 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE"  ENABLE;
  ALTER TABLE "BGH"."BGH_INVOICE_GROUP_RULES" ADD CONSTRAINT "UC_BGH_INVOICE_GROUP_RULES_02" UNIQUE ("RULE_SORT_ORDER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 122880 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE"  ENABLE;
  ALTER TABLE "BGH"."BGH_INVOICE_GROUP_RULES" ADD CONSTRAINT "C_INV_GROUP_CHECK_VARIANT" CHECK (VARIANT_RULE in ('*', 'B', 'BUN','P1','P2','P3','P4','OCC','O1','O2','D', 'IDS', 'F', 'G','P3', 'O1', 'P2','P4')) ENABLE;
  ALTER TABLE "BGH"."BGH_INVOICE_GROUP_RULES" ADD CONSTRAINT "C_INV_GROUP_CHECK_TYPE" CHECK (TYPE_RULE in ('*', 'A', 'S', 'O', 'U', 'P', 'F' )) ENABLE;
  ALTER TABLE "BGH"."BGH_INVOICE_GROUP_RULES" ADD CONSTRAINT "C_INV_GROUP_CHECK_TYPE_INOUT" CHECK (( TYPE_RULE in ('*', 'A', 'S', 'O', 'U', 'P', 'F' ) AND USAGE_BEHAVIOUR_RULE IN ('*', 'Default') )
          OR
          ( TYPE_RULE in ('U') AND USAGE_BEHAVIOUR_RULE IN ('Within Bundle', 'Above Bundle') )) ENABLE;
  ALTER TABLE "BGH"."BGH_INVOICE_GROUP_RULES" ADD CONSTRAINT "C_INV_GROUP_CHECK_DESC_RULE" CHECK (DESC_RULE in ('*')
        OR
        LENGTH(DESC_RULE) > 1) ENABLE;
  ALTER TABLE "BGH"."BGH_INVOICE_GROUP_RULES" ADD CONSTRAINT "C_INV_GROUP_CHECK_INOUT_RULE" CHECK (USAGE_BEHAVIOUR_RULE IN ('*', 'Default'/*, 'Within Bundle', 'Above Bundle'*/)) ENABLE;
  ALTER TABLE "BGH"."BGH_INVOICE_GROUP_RULES" ADD CONSTRAINT "C_INV_GROUP_CHECK_SIGN_RULE" CHECK (SIGN_RULE IN (-1, 0, 1)) ENABLE;
  ALTER TABLE "BGH"."BGH_INVOICE_GROUP_RULES" MODIFY ("RULE_ID" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BGH_INVOICE_GROUP_RULES" MODIFY ("RULE_SORT_ORDER" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BGH_INVOICE_GROUP_RULES" MODIFY ("VARIANT_RULE" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BGH_INVOICE_GROUP_RULES" MODIFY ("TYPE_RULE" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BGH_INVOICE_GROUP_RULES" MODIFY ("DESC_RULE" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BGH_INVOICE_GROUP_RULES" MODIFY ("SIGN_RULE" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BGH_INVOICE_GROUP_RULES" MODIFY ("TMSHDES_RULE" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BGH_INVOICE_GROUP_RULES" MODIFY ("SPSHDES_RULE" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BGH_INVOICE_GROUP_RULES" MODIFY ("SNSHDES_RULE" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BGH_INVOICE_GROUP_RULES" MODIFY ("USAGE_BEHAVIOUR_RULE" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BGH_INVOICE_GROUP_RULES" MODIFY ("GROUP_ID" NOT NULL ENABLE);
