--------------------------------------------------------
--  DDL for Trigger BGH_INVOICE_GROUPS_ON_INS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "BGH"."BGH_INVOICE_GROUPS_ON_INS" 
  BEFORE INSERT ON BGH.BGH_INVOICE_GROUPS
  FOR EACH ROW
BEGIN
  IF INSERTING THEN
    SELECT BGH.BGH_INVOICE_GROUPS_SEQ.NEXTVAL INTO :NEW.GROUP_ID FROM DUAL;
  END IF;
END BGH_INVOICE_GROUPS_ON_INS;

/
ALTER TRIGGER "BGH"."BGH_INVOICE_GROUPS_ON_INS" ENABLE;
