--------------------------------------------------------
--  Ref Constraints for Table BGH_INVOICE_GROUPS
--------------------------------------------------------

  ALTER TABLE "BGH"."BGH_INVOICE_GROUPS" ADD CONSTRAINT "FK_BGH_INVOICE_GROUPS_01" FOREIGN KEY ("FORMAT")
	  REFERENCES "BGH"."PRODUCT_FORMAT" ("FORMAT_SHDES") ENABLE;
  ALTER TABLE "BGH"."BGH_INVOICE_GROUPS" ADD CONSTRAINT "FK_BGH_INVOICE_GROUPS_02" FOREIGN KEY ("GROUP_VARIANT")
	  REFERENCES "BGH"."PRODUCTS_VARIANT" ("VARIANT_SHDES") ENABLE;
