--------------------------------------------------------
--  Constraints for Table BGH_CHARGE_ITEM_CONFIGURATION
--------------------------------------------------------

  ALTER TABLE "BGH"."BGH_CHARGE_ITEM_CONFIGURATION" ADD CONSTRAINT "NCHECK_CHARGE_TYPES" CHECK ((
               CHARGE_TYPE = 'A' AND SNSHDES IS NOT NULL AND SNCODE IS NOT NULL AND INFO1 IS NOT NULL
                  AND USGSHDES IS NULL AND USGIND IS NULL AND ZNSHDES IS NULL AND ZNCODE IS NULL
                  AND RTSHDES IS NULL AND RTID IS NULL
                  AND (
                            INFO2 IS NOT NULL
                            OR
                            (INFO2 IS NULL AND PAD IS NOT NULL AND PAV IS NOT NULL)
														OR
														(INFO2 IS NULL AND PAD IS NULL AND PAV IS NULL)
                      )
           )
           OR
           (
              CHARGE_TYPE = 'S' AND SNSHDES IS NOT NULL AND SNCODE IS NOT NULL AND INFO1 IS NULL
                 AND USGSHDES IS NULL AND USGIND IS NULL AND ZNSHDES IS NULL AND ZNCODE IS NULL
                 AND RTSHDES IS NULL AND RTID IS NULL
                 AND (
                            INFO2 IS NULL
                            OR
                            (INFO2 IS NULL AND (PAD IS NOT NULL AND PAV IS NOT NULL))
                     )
           )
           OR
           (
              CHARGE_TYPE = 'O' AND SNSHDES IS NOT NULL AND SNCODE IS NOT NULL
                 AND INFO1 IS NULL AND INFO2 IS NULL AND PAD IS NULL AND PAV IS NULL
                 AND USGSHDES IS NULL AND USGIND IS NULL AND ZNSHDES IS NULL AND ZNCODE IS NULL
                  AND RTSHDES IS NULL AND RTID IS NULL
           )
					 OR
					 (
              CHARGE_TYPE = 'P' AND SNSHDES IS NULL AND SNCODE IS NULL
                 AND INFO1 IS NOT NULL AND INFO2 IS NOT NULL AND PAD IS NULL AND PAV IS NULL
                 AND USGSHDES IS NULL AND USGIND IS NULL AND ZNSHDES IS NULL AND ZNCODE IS NULL
                  AND RTSHDES IS NULL AND RTID IS NULL
					 )
           OR
           (
              CHARGE_TYPE = 'F' AND INFO1 IS NOT NULL AND INFO2 IS NOT NULL
                AND PAD IS NULL AND PAV IS NULL
                AND SNSHDES IS NULL AND SNCODE IS NULL
                AND USGSHDES IS NULL AND USGIND IS NULL AND ZNSHDES IS NULL AND ZNCODE IS NULL
                AND RTSHDES IS NULL AND RTID IS NULL
           )
           OR
           (
              CHARGE_TYPE = 'U' AND INFO1 IS NULL AND INFO2 IS NULL AND PAD IS NULL AND PAV IS NULL
              AND RTSHDES IS NULL AND RTID IS NULL
              AND (
                        XTMCODE IS NOT NULL
                        OR XSPCODE IS NOT NULL
                        OR SNCODE IS NOT NULL
                        OR USGIND IS NOT NULL
                        OR ZNCODE IS NOT NULL
                  )
           )) ENABLE;
  ALTER TABLE "BGH"."BGH_CHARGE_ITEM_CONFIGURATION" ADD CONSTRAINT "NCHECK_DISPLAY_ZERO_CHARGE" CHECK (DISPLAY_ZERO_CHARGE IN (NULL,'X')) ENABLE;
  ALTER TABLE "BGH"."BGH_CHARGE_ITEM_CONFIGURATION" ADD CONSTRAINT "NCHECK_ITMZED_PID_IS_NULL" CHECK (itemized_product_id IS NULL) ENABLE;
  ALTER TABLE "BGH"."BGH_CHARGE_ITEM_CONFIGURATION" ADD CONSTRAINT "PK_NBGH_CHARGE_ITEM_CONFIG" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 532480 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE"  ENABLE;
  ALTER TABLE "BGH"."BGH_CHARGE_ITEM_CONFIGURATION" ADD CONSTRAINT "UC_BGH_CHARGE_ITEM_CONFIG2_01" UNIQUE ("CHARGE_TYPE", "XTMCODE", "XSPCODE", "SNCODE", "USGIND", "ZNCODE", "RTID", "INFO1", "INFO2", "PAD", "PAV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1064960 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE"  ENABLE;
  ALTER TABLE "BGH"."BGH_CHARGE_ITEM_CONFIGURATION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BGH"."BGH_CHARGE_ITEM_CONFIGURATION" MODIFY ("CHARGE_TYPE" NOT NULL ENABLE);
