--------------------------------------------------------
--  DDL for Index PK_NBGH_CHARGE_ITEM_CONFIG
--------------------------------------------------------

  CREATE UNIQUE INDEX "BGH"."PK_NBGH_CHARGE_ITEM_CONFIG" ON "BGH"."BGH_CHARGE_ITEM_CONFIGURATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 532480 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE" ;
