--------------------------------------------------------
--  Constraints for Table PRODUCT_TYPES
--------------------------------------------------------

  ALTER TABLE "BGH"."PRODUCT_TYPES" ADD PRIMARY KEY ("PRODUCT_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE"  ENABLE;
  ALTER TABLE "BGH"."PRODUCT_TYPES" ADD CONSTRAINT "UI_PRODUCT_TYPES_01" UNIQUE ("PRODUCT_TYPE_SHORT_DESC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE"  ENABLE;
  ALTER TABLE "BGH"."PRODUCT_TYPES" MODIFY ("PRODUCT_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "BGH"."PRODUCT_TYPES" MODIFY ("PRODUCT_TYPE_DESC" NOT NULL ENABLE);
  ALTER TABLE "BGH"."PRODUCT_TYPES" MODIFY ("PRODUCT_TYPE_SHORT_DESC" NOT NULL ENABLE);
