--------------------------------------------------------
--  DDL for Trigger PRODUCTS_VARIANT_ON_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "BGH"."PRODUCTS_VARIANT_ON_INSERT" 
  BEFORE INSERT ON BGH.PRODUCTS_VARIANT
  FOR EACH ROW
BEGIN
  IF INSERTING THEN
    SELECT BGH.PRODUCTS_VARIANT_MAX_ID.NEXTVAL INTO :NEW.variant_ID FROM DUAL;
	END IF;
END PRODUCT_variant_ON_INSERT;

/
ALTER TRIGGER "BGH"."PRODUCTS_VARIANT_ON_INSERT" ENABLE;
