--------------------------------------------------------
--  DDL for Table PRODUCT_TYPES
--------------------------------------------------------

  CREATE TABLE "BGH"."PRODUCT_TYPES" 
   (	"PRODUCT_TYPE_ID" NUMBER, 
	"PRODUCT_TYPE_DESC" VARCHAR2(128 BYTE), 
	"PRODUCT_TYPE_SHORT_DESC" VARCHAR2(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 204800 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE" ;
