--------------------------------------------------------
--  DDL for Table PRODUCTS_VARIANT
--------------------------------------------------------

  CREATE TABLE "BGH"."PRODUCTS_VARIANT" 
   (	"VARIANT_ID" NUMBER, 
	"VARIANT_SHDES" VARCHAR2(10 BYTE), 
	"VARIANT_DES" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE" ;
