REM INSERTING into BGH.PRODUCT_FORMAT
SET DEFINE OFF;
Insert into BGH.PRODUCT_FORMAT (FORMAT_ID,FORMAT_SHDES,FORMAT_DES) values (1,'NO_FORMAT','No Format - Description as is');
Insert into BGH.PRODUCT_FORMAT (FORMAT_ID,FORMAT_SHDES,FORMAT_DES) values (2,'RP_NAME','Replace product (service) with rateplan');
Insert into BGH.PRODUCT_FORMAT (FORMAT_ID,FORMAT_SHDES,FORMAT_DES) values (3,'DEF_ACCFE','Default Access Fee Format (with dates)');
Insert into BGH.PRODUCT_FORMAT (FORMAT_ID,FORMAT_SHDES,FORMAT_DES) values (4,'OCC_STATIC','OCCs display a static description');
Insert into BGH.PRODUCT_FORMAT (FORMAT_ID,FORMAT_SHDES,FORMAT_DES) values (5,'FU_HD_AMT','FUs: Hidden, amount in ?');
Insert into BGH.PRODUCT_FORMAT (FORMAT_ID,FORMAT_SHDES,FORMAT_DES) values (6,'FU_HD_MS','FUs: Hidden, minutes & seconds (mm:ss)');
Insert into BGH.PRODUCT_FORMAT (FORMAT_ID,FORMAT_SHDES,FORMAT_DES) values (7,'FU_HD_NUM','FUs: Hidden, plain number');
Insert into BGH.PRODUCT_FORMAT (FORMAT_ID,FORMAT_SHDES,FORMAT_DES) values (8,'FU_SH_MS','FUs: Shown, minutes & seconds (mm:ss)');
Insert into BGH.PRODUCT_FORMAT (FORMAT_ID,FORMAT_SHDES,FORMAT_DES) values (9,'FU_NZ_AMT','FUs: Show non-zero, amount in ?');
Insert into BGH.PRODUCT_FORMAT (FORMAT_ID,FORMAT_SHDES,FORMAT_DES) values (10,'FU_NZ_MS','FUs: Show non-zero, mins & secs (mm:ss)');
Insert into BGH.PRODUCT_FORMAT (FORMAT_ID,FORMAT_SHDES,FORMAT_DES) values (11,'FU_NZ_NUM','FUs: Show non-zero, plain number');
Insert into BGH.PRODUCT_FORMAT (FORMAT_ID,FORMAT_SHDES,FORMAT_DES) values (12,'FU_SH_NUM','FUs: Shown, plain number');
Insert into BGH.PRODUCT_FORMAT (FORMAT_ID,FORMAT_SHDES,FORMAT_DES) values (13,'FU_PP_HIDE','FUs: Hidden Price Plan FUs');
Insert into BGH.PRODUCT_FORMAT (FORMAT_ID,FORMAT_SHDES,FORMAT_DES) values (14,'FU_SH_AMT','FUs: Shown, monetary amount');
Insert into BGH.PRODUCT_FORMAT (FORMAT_ID,FORMAT_SHDES,FORMAT_DES) values (15,'FU_NZ_MB','FUs: Show non-zero, MBytes');
Insert into BGH.PRODUCT_FORMAT (FORMAT_ID,FORMAT_SHDES,FORMAT_DES) values (16,'FU_SH_MB','FUs: Shown, MBytes');
Insert into BGH.PRODUCT_FORMAT (FORMAT_ID,FORMAT_SHDES,FORMAT_DES) values (17,'FU_HD_MB','FUs: Hidden, MBytes');
Insert into BGH.PRODUCT_FORMAT (FORMAT_ID,FORMAT_SHDES,FORMAT_DES) values (18,'FU_SH_SEC','FUs: Shown, seconds');
Insert into BGH.PRODUCT_FORMAT (FORMAT_ID,FORMAT_SHDES,FORMAT_DES) values (19,'FU_NZ_SEC','FUs: Shown non-zero, seconds');
Insert into BGH.PRODUCT_FORMAT (FORMAT_ID,FORMAT_SHDES,FORMAT_DES) values (20,'FU_HD_SEC','FUs: Hidden, seconds');
