--------------------------------------------------------
--  DDL for Index UC_BGH_CHARGE_ITEM_CONFIG2_01
--------------------------------------------------------

  CREATE UNIQUE INDEX "BGH"."UC_BGH_CHARGE_ITEM_CONFIG2_01" ON "BGH"."BGH_CHARGE_ITEM_CONFIGURATION" ("CHARGE_TYPE", "XTMCODE", "XSPCODE", "SNCODE", "USGIND", "ZNCODE", "RTID", "INFO1", "INFO2", "PAD", "PAV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1064960 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE" ;
