--------------------------------------------------------
--  DDL for Index UC_BGH_STRING_TABLE
--------------------------------------------------------

  CREATE UNIQUE INDEX "BGH"."UC_BGH_STRING_TABLE" ON "BGH"."BGH_STRING_TABLE" ("STRING_LABEL", "STRING_DES", "STRING_DES_EN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 122880 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BEN_LARGE" ;
